---
title: "Breakpoint Analysis"
author: "Indra Boving"
date: "4/15/2021"
output: html_document
---

```{r}
knitr::opts_chunk$set(echo = TRUE)
#lots of extra here, but oh well... 
library(ggplot2)
library(gapminder)
library(tidyverse)
library(lme4)
library(here)
library(segmented)
library(nlme)
filter = dplyr::filter 
```

#------------------------------------
# Data wrangling

### All dates datasets
```{r, message=FALSE, warning=FALSE, include=FALSE}
mem.data.alldates <- read_csv(here("processed-data", "mem.data.local.epi.alldates.csv"), show_col_types = FALSE)

mem.data.raw.alldates <- mem.data.alldates %>%
  mutate(mpa = (-1*mpa)) %>% 
  mutate(year = as.factor(year)) %>%
  mutate(month = as.factor(month)) %>% 
  mutate(mpa.unscaled = mpa) %>% 
  mutate(lfm.unscaled = lfm)%>% 
  mutate(lfm.NAs.imputed.unscaled = lfm.NAs.imputed)
 # mutate(lfm = lfm.NAs.imputed)

clean.mem.data.alldates <- mem.data.raw.alldates
  #na.omit() %>%
  #filter(year.month == "2020_September")

#Parsing out the variables of interest for the mixed effects modelling

clean.mem.data.dependant.alldates <- clean.mem.data.alldates[,c('PC1', 'PC2', 'PC3', 'PC4', 'tti', 'fh', 'gd', 'temp.max', 'flam.index', 'year', 'month', 'prop.ignite', 'prop.ignite.bins5', "ignition")] 
  
scaled.mem.data.predictors.alldates <- clean.mem.data.alldates %>%
    dplyr::select('lfm.NAs.imputed', 'lfm.outliers.out', 'mpa', 'dw.flam.sample', 'sample.wt', 'ww.flam.sample', 'gww.gdw.saturated', 'gdw.gww.saturated', 'lfm') %>%
  scale()
   # dplyr::mutate_if(is.numeric, scale)

mem.data.predictors.alldates <- clean.mem.data.alldates %>%
    dplyr::select('spp', 'year.month', 'individual', 'site', 'start.temp', 'precip.2mo','mpa.unscaled', 'lfm.unscaled', 'lfm.NAs.imputed.unscaled') 

scaled.mem.data.alldates <- cbind(scaled.mem.data.predictors.alldates, 
                         mem.data.predictors.alldates,
                         clean.mem.data.dependant.alldates) 

#For sept. 2020 only: 
scaled.mem.data.alldates <- scaled.mem.data.alldates %>% 
  mutate(Species = case_when(
    spp == "ADFA" ~ "A. fasciculatum", 
    spp == "CEME" ~ "C. megacarpus"
  )) 

scaled.mem.data.alldates.noNAs <- scaled.mem.data.alldates %>% 
  drop_na(mpa, lfm, PC1)

seg.data.subset.alldates <- scaled.mem.data.alldates.noNAs %>% 
  mutate(id = individual) 
#%>% 
 #dplyr::select(id, PC1, PC2, mpa, lfm, ww.flam.sample, dw.flam.sample, spp, tti, mpa.unscaled, prop.ignite, prop.ignite.bins5, fh, gd) 

seg.data.subset.alldates<-seg.data.subset.alldates[order(seg.data.subset.alldates$id),]
```

###2020 datasets
```{r, message=FALSE, warning=FALSE, include=FALSE}
mem.data.2020 <- read_csv(here("processed-data", "mem.data.local.epi.2020.csv"), show_col_types = FALSE)

mem.data.raw.2020 <- mem.data.2020 %>%
  mutate(mpa = (-1*mpa)) %>% 
  mutate(year = as.factor(year)) %>%
  mutate(month = as.factor(month)) %>% 
  mutate(mpa.unscaled = mpa) %>% 
  mutate(lfm.unscaled = lfm) %>% 
  mutate(lfm.NAs.imputed.unscaled = lfm.NAs.imputed)%>% 
  mutate(lfm.unscaled = lfm)
 # mutate(lfm = lfm.NAs.imputed)

clean.mem.data.2020 <- mem.data.raw.2020
  #filter(year.month == "2020_September")

#Parsing out the variables of interest for the mixed effects modelling

#dont scale these:
clean.mem.data.dependant.2020 <- clean.mem.data.2020[,c('PC1', 'PC2', 'PC3', 'PC4', 'tti', 'fh', 'gd', 'temp.max', 'flam.index', 'year', 'month', 'prop.ignite', 'prop.ignite.bins5', "ignition")] 
  
#scale these: 
scaled.mem.data.predictors.2020 <- clean.mem.data.2020 %>%
    dplyr::select('lfm.NAs.imputed', 'lfm.outliers.out', 'mpa', 'dw.flam.sample', 'sample.wt', 'ww.flam.sample', 'gww.gdw.saturated', 'gdw.gww.saturated', 'lfm') %>%
  scale()
   # dplyr::mutate_if(is.numeric, scale)

#dont scale these: 
mem.data.predictors.2020 <- clean.mem.data.2020 %>%
    dplyr::select('spp', 'year.month', 'individual', 'site', 'start.temp', 'precip.2mo','mpa.unscaled', 'lfm.unscaled', 'lfm.NAs.imputed.unscaled', 'bins10lfm') 

scaled.mem.data.2020 <- cbind(scaled.mem.data.predictors.2020, 
                         mem.data.predictors.2020,
                         clean.mem.data.dependant.2020) %>% 
  mutate(Species = case_when(
    spp == "ADFA" ~ "A. fasciculatum", 
    spp == "CEME" ~ "C. megacarpus"
  ))  %>% 
  mutate(id = individual) 

####Dropping NAs

scaled.mem.data.2020.noNAs <- scaled.mem.data.2020 %>% 
  drop_na(lfm, mpa)

seg.data.subset.2020<-scaled.mem.data.2020.noNAs[order(scaled.mem.data.2020.noNAs$id),]
```

These have no NAs: 

```{r, message=FALSE, warning=FALSE, include=FALSE}
seg.adfa.subset <- seg.data.subset.2020  %>% 
  filter(spp == "ADFA") %>% 
  filter(ignition == "1")

seg.CEME.subset <- seg.data.subset.2020  %>% 
  filter(spp == "CEME")%>% 
  filter(ignition == "1")

seg.adfa.subset.allignitions <- seg.data.subset.2020  %>% 
  filter(spp == "ADFA")

seg.ceme.subset.allignitions <- seg.data.subset.2020  %>% 
  filter(spp == "CEME")
```
#Prop.ignite

###MPA

```{r, message=FALSE, results='hide'}
# Separating by Species
p <- ggplot() + 
  geom_point(data= scaled.mem.data.2020.noNAs, aes(mpa.unscaled, prop.ignite, color = Species), size = .7) + 
  #geom_point(data=x_mpa_fig, aes(x=mpa.unscaled, y=fit), color="#7570b3", size = 1) +
 # geom_line(data=x_mpa_fig, aes(x=mpa.unscaled, y=fit), color="#db8872") +
 # geom_ribbon(data= x_mpa_fig, aes(x=mpa.unscaled, ymin=lower, ymax=upper), alpha= 0.3, fill="#db8872") +
  labs(x="Water Potential (-Mpa)",
       y="Prop. Ignite (%)") +
 # scale_color_brewer(name = "Species", palette  = "Dark2") +
  scale_color_manual(values = c("#b08ba5", "#ffb178")) +
  theme_bw() 


p +
  annotate("segment", x = -11.5, xend = -11.5, y = 10, yend = 89,
           colour = "#db8872", size = .7, arrow = arrow(ends = "last", angle = 25, type = "closed", length = unit(.2,"cm"))) +
 # annotate("segment", x = -9, xend = -1, y = -4, yend = -4,
          # colour = "#7570b3", size = .7, arrow = arrow(ends = "last", angle = 25, type = "closed", length = unit(.2,"cm")))  +
  annotate("text", x= -11.5, y= 98, label= "More", size = 3) +
  annotate("text", x= -11.5, y= 92.5, label= "Flammable", size = 3)+
annotate("text", x= -11.5, y= 8, label= "Less", size = 3) +
  annotate("text", x= -11.5, y= 2, label= "Flammable", size = 3)  +
  theme_bw() +
  scale_x_continuous(limits = c(-12.5, 0), breaks= c(-10, -8, -6, -4, -2, 0))
```
### LFM

```{r, message=FALSE, results='hide'}
# Separating by Species
p <- ggplot() + 
  geom_point(data= scaled.mem.data.2020.noNAs, aes(lfm.unscaled, prop.ignite, color = Species), size = .7) + 
  #geom_point(data=x_mpa_fig, aes(x=mpa.unscaled, y=fit), color="#7570b3", size = 1) +
 # geom_line(data=x_mpa_fig, aes(x=mpa.unscaled, y=fit), color="#db8872") +
 # geom_ribbon(data= x_mpa_fig, aes(x=mpa.unscaled, ymin=lower, ymax=upper), alpha= 0.3, fill="#db8872") +
  labs(x="LFM",
       y="Prop. Ignite (%)") +
 # scale_color_brewer(name = "Species", palette  = "Dark2") +
  scale_color_manual(values = c("#b08ba5", "#ffb178")) +
  theme_bw() 

p +
  annotate("segment", x = -15, xend = -15, y = 10, yend = 89,
           colour = "#db8872", size = .7, arrow = arrow(ends = "last", angle = 25, type = "closed", length = unit(.2,"cm"))) +
 # annotate("segment", x = -9, xend = -1, y = -4, yend = -4,
          # colour = "#7570b3", size = .7, arrow = arrow(ends = "last", angle = 25, type = "closed", length = unit(.2,"cm")))  +
  annotate("text", x= -15, y= 98, label= "More", size = 3) +
  annotate("text", x= -15, y= 92.5, label= "Flammable", size = 3)+
annotate("text", x= -15, y= 8, label= "Less", size = 3) +
  annotate("text", x= -15, y= 2, label= "Flammable", size = 3)  +
  theme_bw() +
  scale_x_continuous(limits = c(-30, 160), breaks= c(0, 60, 80, 160))
```
```{r, message=FALSE, results='hide'}

# Separating by Species
p <- ggplot() + 
  geom_col(data= scaled.mem.data.2020.noNAs, aes(bins10lfm, prop.ignite, fill = Species), position = 'dodge') + 
  #geom_point(data=x_mpa_fig, aes(x=mpa.unscaled, y=fit), color="#7570b3", size = 1) +
 # geom_line(data=x_mpa_fig, aes(x=mpa.unscaled, y=fit), color="#db8872") +
 # geom_ribbon(data= x_mpa_fig, aes(x=mpa.unscaled, ymin=lower, ymax=upper), alpha= 0.3, fill="#db8872") +
  labs(x="LFM",
       y="Prop. Ignite (%)") +
 # scale_color_brewer(name = "Species", palette  = "Dark2") +
  scale_fill_manual(values = c("#b08ba5", "#ffb178")) +
  theme_bw() 
p

p +
  annotate("segment", x = -15, xend = -15, y = 10, yend = 89,
           colour = "#db8872", size = .7, arrow = arrow(ends = "last", angle = 25, type = "closed", length = unit(.2,"cm"))) +
 # annotate("segment", x = -9, xend = -1, y = -4, yend = -4,
          # colour = "#7570b3", size = .7, arrow = arrow(ends = "last", angle = 25, type = "closed", length = unit(.2,"cm")))  +
  annotate("text", x= -15, y= 98, label= "More", size = 3) +
  annotate("text", x= -15, y= 92.5, label= "Flammable", size = 3)+
annotate("text", x= -15, y= 8, label= "Less", size = 3) +
  annotate("text", x= -15, y= 2, label= "Flammable", size = 3)  +
  theme_bw() 
```
#Segmented regressions: 

# LFM 

## ADFA

```{r}
out.lm<-lm(PC1 ~ lfm, data = seg.adfa.subset)

#the simplest example: the starting model includes just 1 covariate
#.. and 1 breakpoint has to be estimated for that
o_adfa_lfm <-segmented(out.lm) #1 breakpoint for x
o_adfa_lfm
```

```{r}
plot(o_adfa_lfm, conf.level=.9, is=TRUE, isV=FALSE, col=2, shade = TRUE, res=TRUE, res.col=4, pch=3)
```

## CEME

```{r}
out.lm<-lm(PC1 ~ lfm, data = seg.CEME.subset)

#the simplest example: the starting model includes just 1 covariate
#.. and 1 breakpoint has to be estimated for that
o_CEME_lfm <-segmented(out.lm) #1 breakpoint for x
o_CEME_lfm
```
```{r}
plot(o_CEME_lfm, conf.level=.9, is=TRUE, isV=FALSE, col=2, shade = TRUE, res=TRUE, res.col=4, pch=3)
```
# Mpa

## ADFA

```{r}
out.lm<-lm(PC1 ~ mpa, data = seg.adfa.subset)

#the simplest example: the starting model includes just 1 covariate
#.. and 1 breakpoint has to be estimated for that
o_adfa_mpa <-segmented(out.lm) #1 breakpoint for x
o_adfa_mpa
```


```{r}
plot(o_adfa_mpa, conf.level=.9, is=TRUE, isV=FALSE, col=2, shade = TRUE, res=TRUE, res.col=4, pch=3)
```

## CEME

```{r}
out.lm<-lm(PC1 ~ mpa, data = seg.CEME.subset)

#the simplest example: the starting model includes just 1 covariate
#.. and 1 breakpoint has to be estimated for that
o_CEME_mpa <-segmented(out.lm) #1 breakpoint for x
o_CEME_mpa
```

```{r}
plot(o_CEME_mpa, conf.level=.9, is=TRUE, isV=FALSE, col=2, shade = TRUE, res=TRUE, res.col=4, pch=3)
```

#Prop. ignite v MPA

## ADFA

```{r}
out.lm<-lm(prop.ignite ~ mpa, data = seg.adfa.subset)

#the simplest example: the starting model includes just 1 covariate
#.. and 1 breakpoint has to be estimated for that
o_adfa_mpa <-segmented(out.lm) #1 breakpoint for x
o_adfa_mpa
```


```{r}
plot(o_adfa_mpa, conf.level=.9, is=TRUE, isV=FALSE, col=2, shade = TRUE, res=TRUE, res.col=4, pch=3)
```

## CEME

```{r}
out.lm<-lm(prop.ignite ~ mpa, data = seg.CEME.subset)

#the simplest example: the starting model includes just 1 covariate
#.. and 1 breakpoint has to be estimated for that
o_CEME_mpa <-segmented(out.lm) #1 breakpoint for x
o_CEME_mpa
```

```{r}
plot(o_CEME_mpa, conf.level=.9, is=TRUE, isV=FALSE, col=2, shade = TRUE, res=TRUE, res.col=4, pch=3)
```

# Zoomed in Prop Ignite

## Prop. ignite v LFM 

### ADFA

```{r}
out.lm<-lm(prop.ignite.bins5 ~ lfm, data = seg.adfa.subset)

#the simplest example: the starting model includes just 1 covariate
#.. and 1 breakpoint has to be estimated for that
o_adfa_lfm <-segmented(out.lm) #1 breakpoint for x
o_adfa_lfm
```

```{r}
plot(o_adfa_lfm, conf.level=.9, is=TRUE, isV=FALSE, col=2, shade = TRUE, res=TRUE, res.col=4, pch=3)
```

##Prop. ignite v MPA

### ADFA

```{r}
out.lm<-lm(prop.ignite.bins5 ~ mpa, data = seg.adfa.subset)

#the simplest example: the starting model includes just 1 covariate
#.. and 1 breakpoint has to be estimated for that
o_adfa_mpa <-segmented(out.lm) #1 breakpoint for x
o_adfa_mpa
```


```{r}
plot(o_adfa_mpa, conf.level=.9, is=TRUE, isV=FALSE, col=2, shade = TRUE, res=TRUE, res.col=4, pch=3)
```

### CEME

```{r}
out.lm<-lm(prop.ignite.bins5 ~ mpa, data = seg.CEME.subset)

#the simplest example: the starting model includes just 1 covariate
#.. and 1 breakpoint has to be estimated for that
o_CEME_mpa <-segmented(out.lm) #1 breakpoint for x
o_CEME_mpa
```

```{r}
plot(o_CEME_mpa, conf.level=.9, is=TRUE, isV=FALSE, col=2, shade = TRUE, res=TRUE, res.col=4, pch=3)
```

## prop.ignite.bins5 v LFM 

### ADFA

```{r}
out.lm<-lm(prop.ignite.bins5 ~ lfm, data = seg.adfa.subset)

#the simplest example: the starting model includes just 1 covariate
#.. and 1 breakpoint has to be estimated for that
o_adfa_lfm <-segmented(out.lm) #1 breakpoint for x
o_adfa_lfm
```

```{r}
plot(o_adfa_lfm, conf.level=.9, is=TRUE, isV=FALSE, col=2, shade = TRUE, res=TRUE, res.col=4, pch=3)
```

### CEME

```{r}
out.lm<-lm(prop.ignite.bins5 ~ lfm, data = seg.CEME.subset)

#the simplest example: the starting model includes just 1 covariate
#.. and 1 breakpoint has to be estimated for that
o_CEME_lfm <-segmented(out.lm) #1 breakpoint for x
o_CEME_lfm
```

```{r}
plot(o_CEME_lfm, conf.level=.9, is=TRUE, isV=FALSE, col=2, shade = TRUE, res=TRUE, res.col=4, pch=3)

plot(o_CEME_lfm)
```

