---
title: "`grateful` citation report"
bibliography: grateful-refs.bib
csl: https://github.com/citation-style-language/styles/blob/master/dependent/functional-ecology.csl.csl
---

## R packages used

<table>
 <thead>
  <tr>
   <th style="text-align:left;"> Package </th>
   <th style="text-align:left;"> Version </th>
   <th style="text-align:left;"> Citation </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> AICcmodavg </td>
   <td style="text-align:left;"> 2.3.1 </td>
   <td style="text-align:left;"> @AICcmodavg </td>
  </tr>
  <tr>
   <td style="text-align:left;"> base </td>
   <td style="text-align:left;"> 4.2.2 </td>
   <td style="text-align:left;"> @base </td>
  </tr>
  <tr>
   <td style="text-align:left;"> broom.mixed </td>
   <td style="text-align:left;"> 0.2.9.4 </td>
   <td style="text-align:left;"> @broommixed </td>
  </tr>
  <tr>
   <td style="text-align:left;"> cowplot </td>
   <td style="text-align:left;"> 1.1.1 </td>
   <td style="text-align:left;"> @cowplot </td>
  </tr>
  <tr>
   <td style="text-align:left;"> data.table </td>
   <td style="text-align:left;"> 1.14.6 </td>
   <td style="text-align:left;"> @datatable </td>
  </tr>
  <tr>
   <td style="text-align:left;"> devtools </td>
   <td style="text-align:left;"> 2.4.5 </td>
   <td style="text-align:left;"> @devtools </td>
  </tr>
  <tr>
   <td style="text-align:left;"> dlookr </td>
   <td style="text-align:left;"> 0.6.1 </td>
   <td style="text-align:left;"> @dlookr </td>
  </tr>
  <tr>
   <td style="text-align:left;"> effects </td>
   <td style="text-align:left;"> 4.2.2 </td>
   <td style="text-align:left;"> @effects2003; @effects2009; @effects2018; @effects2019 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> equatiomatic </td>
   <td style="text-align:left;"> 0.3.1 </td>
   <td style="text-align:left;"> @equatiomatic </td>
  </tr>
  <tr>
   <td style="text-align:left;"> gapminder </td>
   <td style="text-align:left;"> 0.3.0 </td>
   <td style="text-align:left;"> @gapminder </td>
  </tr>
  <tr>
   <td style="text-align:left;"> GGally </td>
   <td style="text-align:left;"> 2.1.2 </td>
   <td style="text-align:left;"> @GGally </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ggbiplot </td>
   <td style="text-align:left;"> 0.55 </td>
   <td style="text-align:left;"> @ggbiplot </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ggeffects </td>
   <td style="text-align:left;"> 1.1.4 </td>
   <td style="text-align:left;"> @ggeffects </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ggfortify </td>
   <td style="text-align:left;"> 0.4.15 </td>
   <td style="text-align:left;"> @ggfortify2016; @ggfortify2018 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ggpubr </td>
   <td style="text-align:left;"> 0.5.0 </td>
   <td style="text-align:left;"> @ggpubr </td>
  </tr>
  <tr>
   <td style="text-align:left;"> glmmTMB </td>
   <td style="text-align:left;"> 1.1.5 </td>
   <td style="text-align:left;"> @glmmTMB </td>
  </tr>
  <tr>
   <td style="text-align:left;"> gridExtra </td>
   <td style="text-align:left;"> 2.3 </td>
   <td style="text-align:left;"> @gridExtra </td>
  </tr>
  <tr>
   <td style="text-align:left;"> gt </td>
   <td style="text-align:left;"> 0.9.0 </td>
   <td style="text-align:left;"> @gt </td>
  </tr>
  <tr>
   <td style="text-align:left;"> gtsummary </td>
   <td style="text-align:left;"> 1.7.1 </td>
   <td style="text-align:left;"> @gtsummary </td>
  </tr>
  <tr>
   <td style="text-align:left;"> here </td>
   <td style="text-align:left;"> 1.0.1 </td>
   <td style="text-align:left;"> @here </td>
  </tr>
  <tr>
   <td style="text-align:left;"> janitor </td>
   <td style="text-align:left;"> 2.1.0 </td>
   <td style="text-align:left;"> @janitor </td>
  </tr>
  <tr>
   <td style="text-align:left;"> jtools </td>
   <td style="text-align:left;"> 2.2.0 </td>
   <td style="text-align:left;"> @jtools </td>
  </tr>
  <tr>
   <td style="text-align:left;"> kableExtra </td>
   <td style="text-align:left;"> 1.3.4 </td>
   <td style="text-align:left;"> @kableExtra </td>
  </tr>
  <tr>
   <td style="text-align:left;"> kimisc </td>
   <td style="text-align:left;"> 0.4 </td>
   <td style="text-align:left;"> @kimisc </td>
  </tr>
  <tr>
   <td style="text-align:left;"> knitr </td>
   <td style="text-align:left;"> 1.40 </td>
   <td style="text-align:left;"> @knitr2014; @knitr2015; @knitr2022 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> lattice </td>
   <td style="text-align:left;"> 0.20.45 </td>
   <td style="text-align:left;"> @lattice </td>
  </tr>
  <tr>
   <td style="text-align:left;"> lme4 </td>
   <td style="text-align:left;"> 1.1.31 </td>
   <td style="text-align:left;"> @lme4 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> lmerTest </td>
   <td style="text-align:left;"> 3.1.3 </td>
   <td style="text-align:left;"> @lmerTest </td>
  </tr>
  <tr>
   <td style="text-align:left;"> MetBrewer </td>
   <td style="text-align:left;"> 0.2.0 </td>
   <td style="text-align:left;"> @MetBrewer </td>
  </tr>
  <tr>
   <td style="text-align:left;"> modelsummary </td>
   <td style="text-align:left;"> 1.1.0 </td>
   <td style="text-align:left;"> @modelsummary </td>
  </tr>
  <tr>
   <td style="text-align:left;"> MuMIn </td>
   <td style="text-align:left;"> 1.47.1 </td>
   <td style="text-align:left;"> @MuMIn </td>
  </tr>
  <tr>
   <td style="text-align:left;"> naniar </td>
   <td style="text-align:left;"> 0.6.1 </td>
   <td style="text-align:left;"> @naniar </td>
  </tr>
  <tr>
   <td style="text-align:left;"> nlme </td>
   <td style="text-align:left;"> 3.1.160 </td>
   <td style="text-align:left;"> @nlme2000; @nlme2022 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> performance </td>
   <td style="text-align:left;"> 0.10.0 </td>
   <td style="text-align:left;"> @performance </td>
  </tr>
  <tr>
   <td style="text-align:left;"> plotrix </td>
   <td style="text-align:left;"> 3.8.2 </td>
   <td style="text-align:left;"> @plotrix </td>
  </tr>
  <tr>
   <td style="text-align:left;"> psych </td>
   <td style="text-align:left;"> 2.2.9 </td>
   <td style="text-align:left;"> @psych </td>
  </tr>
  <tr>
   <td style="text-align:left;"> remef </td>
   <td style="text-align:left;"> 1.0.7 </td>
   <td style="text-align:left;"> @remef </td>
  </tr>
  <tr>
   <td style="text-align:left;"> remotes </td>
   <td style="text-align:left;"> 2.4.2 </td>
   <td style="text-align:left;"> @remotes </td>
  </tr>
  <tr>
   <td style="text-align:left;"> rmarkdown </td>
   <td style="text-align:left;"> 2.18 </td>
   <td style="text-align:left;"> @rmarkdown2018; @rmarkdown2020; @rmarkdown2022 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> scales </td>
   <td style="text-align:left;"> 1.2.1 </td>
   <td style="text-align:left;"> @scales </td>
  </tr>
  <tr>
   <td style="text-align:left;"> segmented </td>
   <td style="text-align:left;"> 1.5.0 </td>
   <td style="text-align:left;"> @segmented2003; @segmented2008; @segmented2016; @segmented2017 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> simputation </td>
   <td style="text-align:left;"> 0.2.8 </td>
   <td style="text-align:left;"> @simputation </td>
  </tr>
  <tr>
   <td style="text-align:left;"> sjmisc </td>
   <td style="text-align:left;"> 2.8.9 </td>
   <td style="text-align:left;"> @sjmisc </td>
  </tr>
  <tr>
   <td style="text-align:left;"> sjPlot </td>
   <td style="text-align:left;"> 2.8.11 </td>
   <td style="text-align:left;"> @sjPlot </td>
  </tr>
  <tr>
   <td style="text-align:left;"> sjstats </td>
   <td style="text-align:left;"> 0.18.1 </td>
   <td style="text-align:left;"> @sjstats </td>
  </tr>
  <tr>
   <td style="text-align:left;"> strengejacke </td>
   <td style="text-align:left;"> 0.5.0 </td>
   <td style="text-align:left;"> @strengejacke </td>
  </tr>
  <tr>
   <td style="text-align:left;"> tidyverse </td>
   <td style="text-align:left;"> 1.3.2 </td>
   <td style="text-align:left;"> @tidyverse </td>
  </tr>
  <tr>
   <td style="text-align:left;"> TMB </td>
   <td style="text-align:left;"> 1.9.1 </td>
   <td style="text-align:left;"> @TMB2016; @TMB2017 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> visdat </td>
   <td style="text-align:left;"> 0.5.3 </td>
   <td style="text-align:left;"> @visdat </td>
  </tr>
</tbody>
</table>

**You can paste this paragraph directly in your report:**

We used R version 4.2.2 [@base] and the following R packages: AICcmodavg v. 2.3.1 [@AICcmodavg], broom.mixed v. 0.2.9.4 [@broommixed], cowplot v. 1.1.1 [@cowplot], data.table v. 1.14.6 [@datatable], devtools v. 2.4.5 [@devtools], dlookr v. 0.6.1 [@dlookr], effects v. 4.2.2 [@effects2003; @effects2009; @effects2018; @effects2019], equatiomatic v. 0.3.1 [@equatiomatic], gapminder v. 0.3.0 [@gapminder], GGally v. 2.1.2 [@GGally], ggbiplot v. 0.55 [@ggbiplot], ggeffects v. 1.1.4 [@ggeffects], ggfortify v. 0.4.15 [@ggfortify2016; @ggfortify2018], ggpubr v. 0.5.0 [@ggpubr], glmmTMB v. 1.1.5 [@glmmTMB], gridExtra v. 2.3 [@gridExtra], gt v. 0.9.0 [@gt], gtsummary v. 1.7.1 [@gtsummary], here v. 1.0.1 [@here], janitor v. 2.1.0 [@janitor], jtools v. 2.2.0 [@jtools], kableExtra v. 1.3.4 [@kableExtra], kimisc v. 0.4 [@kimisc], knitr v. 1.40 [@knitr2014; @knitr2015; @knitr2022], lattice v. 0.20.45 [@lattice], lme4 v. 1.1.31 [@lme4], lmerTest v. 3.1.3 [@lmerTest], MetBrewer v. 0.2.0 [@MetBrewer], modelsummary v. 1.1.0 [@modelsummary], MuMIn v. 1.47.1 [@MuMIn], naniar v. 0.6.1 [@naniar], nlme v. 3.1.160 [@nlme2000; @nlme2022], performance v. 0.10.0 [@performance], plotrix v. 3.8.2 [@plotrix], psych v. 2.2.9 [@psych], remef v. 1.0.7 [@remef], remotes v. 2.4.2 [@remotes], rmarkdown v. 2.18 [@rmarkdown2018; @rmarkdown2020; @rmarkdown2022], scales v. 1.2.1 [@scales], segmented v. 1.5.0 [@segmented2003; @segmented2008; @segmented2016; @segmented2017], simputation v. 0.2.8 [@simputation], sjmisc v. 2.8.9 [@sjmisc], sjPlot v. 2.8.11 [@sjPlot], sjstats v. 0.18.1 [@sjstats], strengejacke v. 0.5.0 [@strengejacke], tidyverse v. 1.3.2 [@tidyverse], TMB v. 1.9.1 [@TMB2016; @TMB2017], visdat v. 0.5.3 [@visdat].

## Package citations

